# Generated by Django 4.2.4 on 2023-09-12 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
